version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: node index.js

  frontend:
    build:
      context: ./NavDev
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./NavDev:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: serve -s dist -l 5173
